@startuml
left to right direction
actor "Producer" as producer
actor "Consumer" as consumer

rectangle fifo {
  usecase "put" as put
  usecase "reset" as reset 
  usecase "is_full" as full
  usecase "get" as get
  usecase "is_emtpy" as empty
}

producer --> put
producer --> reset
producer --> full
consumer --> get
consumer --> empty
@enduml